#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "esp_log.h"
#include "esp_attr.h"
#include "esp_system.h"
#include "spi_flash_mmap.h"
#include "esp_flash.h"
#include "esp_heap_caps.h"
#include <inttypes.h>
#include "CNN.h"
#include <math.h>
#include "camera.h"
static const char *TAG = "CNN";

// ── Network dimensions ────────────────────────────────────────────────────────
#define IN_CH      1
#define IN_H       64
#define IN_W       64
#define CONV1_OUT  16
#define CONV2_OUT  32
#define CONV3_OUT  64
#define FC_OUT     3

// ── Binary blob (embedded via CMake / component.mk) ──────────────────────────
extern const int8_t model_weights_bin_start[] asm("_binary_model_weights_bin_start");
extern const int8_t model_weights_bin_end[]   asm("_binary_model_weights_bin_end");

// ── Quantization scales  (generated by quantizer.py) ─────────────────────────
const float conv2d_6_bias_scale    = 0.0081939697f;
const float conv2d_6_weight_scale  = 0.0516016465f;
const float conv2d_7_bias_scale    = 0.0159369341f;
const float conv2d_7_weight_scale  = 0.0044655209f;
const float conv2d_8_bias_scale    = 0.0184028918f;
const float conv2d_8_weight_scale  = 0.0071526813f;
const float dense_2_bias_scale     = 0.0020740323f;
const float dense_2_weight_scale   = 0.0061456669f;


#define CONV2D_6_BIAS_QUANTIZED_SIZE    16
#define CONV2D_6_WEIGHT_QUANTIZED_SIZE  144
#define CONV2D_7_BIAS_QUANTIZED_SIZE    32
#define CONV2D_7_WEIGHT_QUANTIZED_SIZE  4608
#define CONV2D_8_BIAS_QUANTIZED_SIZE    64
#define CONV2D_8_WEIGHT_QUANTIZED_SIZE  18432
#define DENSE_2_BIAS_QUANTIZED_SIZE     3
#define DENSE_2_WEIGHT_QUANTIZED_SIZE   192

// ── Activation buffers (PSRAM) ────────────────────────────────────────────────
float   *conv1_buf = NULL;
float   *conv2_buf = NULL;
float   *conv3_buf = NULL;
float   *gap_buf   = NULL;
float   *fc_out    = NULL;
float   *image_fp  = NULL;
uint8_t *im        = NULL;

// ── Class names ───────────────────────────────────────────────────────────────
const char *CLASS_NAMES[FC_OUT] = {"Back", "Stomach", "Side"};

static cnn_prediction_t s_last_prediction = {
    .class_name = "Waiting...",
    .confidence = 0.0f,
    .prob       = {0.0f, 0.0f, 0.0f}
};

cnn_prediction_t cnn_get_last_prediction(void) { return s_last_prediction; }

// ─────────────────────────────────────────────────────────────────────────────
// Allocate PSRAM buffers — call once at startup
// ─────────────────────────────────────────────────────────────────────────────
void cnn_allocate_buffers(void)
{
    im        = heap_caps_malloc(IN_H * IN_W,                         MALLOC_CAP_SPIRAM);
    image_fp  = heap_caps_malloc(IN_H * IN_W * sizeof(float),         MALLOC_CAP_SPIRAM);
    conv1_buf = heap_caps_malloc(CONV1_OUT * 64 * 64 * sizeof(float), MALLOC_CAP_SPIRAM);
    conv2_buf = heap_caps_malloc(CONV2_OUT * 32 * 32 * sizeof(float), MALLOC_CAP_SPIRAM);
    conv3_buf = heap_caps_malloc(CONV3_OUT * 16 * 16 * sizeof(float), MALLOC_CAP_SPIRAM);
    gap_buf   = heap_caps_malloc(CONV3_OUT * sizeof(float),           MALLOC_CAP_SPIRAM);
    fc_out    = heap_caps_malloc(FC_OUT    * sizeof(float),           MALLOC_CAP_SPIRAM);

    if (!im || !image_fp || !conv1_buf || !conv2_buf ||
        !conv3_buf || !gap_buf || !fc_out) {
        ESP_LOGE(TAG, "Failed to allocate CNN buffers — not enough PSRAM");
        abort();
    }
    ESP_LOGI(TAG, "CNN buffers allocated (PSRAM)");
}

// ─────────────────────────────────────────────────────────────────────────────
// conv2d  —  same-padded, stride 1, quantized int8 weights
//
// Binary layout per layer (set by quantizer.py):
//   b_start = bin + off                       (bias bytes)
//   w_start = bin + off + BIAS_QUANTIZED_SIZE (weight bytes)
// ─────────────────────────────────────────────────────────────────────────────
void conv(const float   *input,  float *output,
          const int8_t  *w_start, const int8_t *b_start,
          float w_scale, float b_scale,
          size_t in_ch, size_t out_ch,
          size_t H, size_t W,
          size_t kH, size_t kW, size_t stride)
{
    const size_t HW     = H * W;
    const size_t kHW    = kH * kW;
    const size_t per_oc = in_ch * kHW;
    const int    outH   = (int)H;
    const int    outW   = (int)W;
    const int    outHW  = outH * outW;
    const int    pad_h  = (int)(kH / 2);
    const int    pad_w  = (int)(kW / 2);

    // Dequantize biases once
    float bias_fp[128];
    for (size_t oc = 0; oc < out_ch; oc++)
        bias_fp[oc] = b_start[oc] * b_scale;

    for (size_t oc = 0; oc < out_ch; oc++) {
        float        *out_ptr = output + oc * outHW;
        const int8_t *w_oc   = w_start + oc * per_oc;

        // Initialise with bias
        for (int i = 0; i < outHW; i++)
            out_ptr[i] = bias_fp[oc];

        for (size_t ic = 0; ic < in_ch; ic++) {
            const float  *in_ic = input  + ic * HW;
            const int8_t *w_ic  = w_oc   + ic * kHW;

            // Dequantize kernel once per (oc, ic) pair
            float w_fp[9];
            for (size_t k = 0; k < kHW; k++)
                w_fp[k] = w_ic[k] * w_scale;

            if (kH == 3 && kW == 3) {
                // ── Fast inner loop: interior pixels (no boundary checks) ──
                for (int oy = 1; oy < outH - 1; oy++) {
                    int          iy = oy - pad_h;
                    const float *r0 = in_ic + iy * W;
                    const float *r1 = r0 + W;
                    const float *r2 = r1 + W;
                    for (int ox = 1; ox < outW - 1; ox++) {
                        int ix = ox - pad_w;
                        out_ptr[oy * outW + ox] +=
                            r0[ix]   * w_fp[0] + r0[ix+1] * w_fp[1] + r0[ix+2] * w_fp[2] +
                            r1[ix]   * w_fp[3] + r1[ix+1] * w_fp[4] + r1[ix+2] * w_fp[5] +
                            r2[ix]   * w_fp[6] + r2[ix+1] * w_fp[7] + r2[ix+2] * w_fp[8];
                    }
                }
                // ── Top and bottom border rows ──
                for (int oy = 0; oy < outH; oy++) {
                    if (oy > 0 && oy < outH - 1) continue;
                    int iy_base = oy * (int)stride - pad_h;
                    for (int ox = 0; ox < outW; ox++) {
                        int   ix_base = ox * (int)stride - pad_w;
                        float sum     = 0.0f;
                        for (int ky = 0; ky < 3; ky++) {
                            int iy = iy_base + ky;
                            if ((unsigned)iy >= (unsigned)H) continue;
                            const float *row = in_ic + iy * W;
                            int ix0 = ix_base, ix1 = ix_base+1, ix2 = ix_base+2;
                            if ((unsigned)ix0 < (unsigned)W) sum += row[ix0] * w_fp[ky*3];
                            if ((unsigned)ix1 < (unsigned)W) sum += row[ix1] * w_fp[ky*3+1];
                            if ((unsigned)ix2 < (unsigned)W) sum += row[ix2] * w_fp[ky*3+2];
                        }
                        out_ptr[oy * outW + ox] += sum;
                    }
                }
                // ── Left and right border columns ──
                for (int oy = 1; oy < outH - 1; oy++) {
                    int iy_base = oy * (int)stride - pad_h;
                    for (int ox = 0; ox < outW; ox++) {
                        if (ox > 0 && ox < outW - 1) continue;
                        int   ix_base = ox * (int)stride - pad_w;
                        float sum     = 0.0f;
                        for (int ky = 0; ky < 3; ky++) {
                            int          iy  = iy_base + ky;
                            const float *row = in_ic + iy * W;
                            int ix0 = ix_base, ix1 = ix_base+1, ix2 = ix_base+2;
                            if ((unsigned)ix0 < (unsigned)W) sum += row[ix0] * w_fp[ky*3];
                            if ((unsigned)ix1 < (unsigned)W) sum += row[ix1] * w_fp[ky*3+1];
                            if ((unsigned)ix2 < (unsigned)W) sum += row[ix2] * w_fp[ky*3+2];
                        }
                        out_ptr[oy * outW + ox] += sum;
                    }
                }
            } else {
                // ── Generic kernel size fallback ──
                int out_idx = 0;
                for (int oy = 0; oy < outH; oy++) {
                    int iy_base = oy * (int)stride - pad_h;
                    for (int ox = 0; ox < outW; ox++, out_idx++) {
                        int   ix_base = ox * (int)stride - pad_w;
                        float sum     = 0.0f;
                        for (size_t ky = 0; ky < kH; ky++) {
                            int iy = iy_base + (int)ky;
                            if ((unsigned)iy >= (unsigned)H) continue;
                            const float *row   = in_ic + iy * W;
                            const float *w_row = w_fp  + ky * kW;
                            for (size_t kx = 0; kx < kW; kx++) {
                                int ix = ix_base + (int)kx;
                                if ((unsigned)ix >= (unsigned)W) continue;
                                sum += row[ix] * w_row[kx];
                            }
                        }
                        out_ptr[out_idx] += sum;
                    }
                }
            }
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
void global_avg_pool(const float *in, float *out, int C, int H, int W)
{
    int HW = H * W;
    for (int c = 0; c < C; c++) {
        float        sum = 0.0f;
        const float *p   = in + c * HW;
        for (int i = 0; i < HW; i++) sum += p[i];
        out[c] = sum / HW;
    }
}

void maxpool2x2(const float *input, float *output,
                size_t in_ch, size_t H, size_t W)
{
    size_t outH  = H / 2;
    size_t outW  = W / 2;
    size_t HW    = H * W;
    size_t outHW = outH * outW;

    for (size_t c = 0; c < in_ch; c++) {
        const float *in_c  = input  + c * HW;
        float       *out_c = output + c * outHW;
        for (size_t oy = 0; oy < outH; oy++) {
            size_t iy = oy * 2;
            for (size_t ox = 0; ox < outW; ox++) {
                size_t       ix   = ox * 2;
                const float *row0 = in_c + iy * W;
                const float *row1 = row0 + W;
                float a  = row0[ix],  b  = row0[ix+1];
                float c_ = row1[ix],  d  = row1[ix+1];
                float m1 = (a  > b  ? a  : b);
                float m2 = (c_ > d  ? c_ : d);
                out_c[oy * outW + ox] = (m1 > m2 ? m1 : m2);
            }
        }
    }
}

void fc(const float  *input,  float *output,
        size_t in_size, size_t out_size,
        const int8_t *w_start, const int8_t *b_start,
        float w_scale, float b_scale)
{
    for (size_t o = 0; o < out_size; o++) {
        const int8_t *w   = w_start + o * in_size;
        float         sum = b_start[o] * b_scale;
        size_t i = 0;
        for (; i + 7 < in_size; i += 8) {
            sum += input[i]   * (w[i]   * w_scale);
            sum += input[i+1] * (w[i+1] * w_scale);
            sum += input[i+2] * (w[i+2] * w_scale);
            sum += input[i+3] * (w[i+3] * w_scale);
            sum += input[i+4] * (w[i+4] * w_scale);
            sum += input[i+5] * (w[i+5] * w_scale);
            sum += input[i+6] * (w[i+6] * w_scale);
            sum += input[i+7] * (w[i+7] * w_scale);
        }
        for (; i < in_size; i++)
            sum += input[i] * (w[i] * w_scale);
        output[o] = sum;
    }
}

void relu(float *x, size_t size)
{
    size_t i = 0;
    for (; i + 7 < size; i += 8) {
        x[i]   = x[i]   > 0.0f ? x[i]   : 0.0f;
        x[i+1] = x[i+1] > 0.0f ? x[i+1] : 0.0f;
        x[i+2] = x[i+2] > 0.0f ? x[i+2] : 0.0f;
        x[i+3] = x[i+3] > 0.0f ? x[i+3] : 0.0f;
        x[i+4] = x[i+4] > 0.0f ? x[i+4] : 0.0f;
        x[i+5] = x[i+5] > 0.0f ? x[i+5] : 0.0f;
        x[i+6] = x[i+6] > 0.0f ? x[i+6] : 0.0f;
        x[i+7] = x[i+7] > 0.0f ? x[i+7] : 0.0f;
    }
    for (; i < size; i++)
        x[i] = x[i] > 0.0f ? x[i] : 0.0f;
}

void softmax(const float *input, float *output, int size)
{
    float max_val = input[0];
    for (int i = 1; i < size; i++)
        if (input[i] > max_val) max_val = input[i];
    float sum = 0.0f;
    for (int i = 0; i < size; i++) {
        output[i] = expf(input[i] - max_val);
        sum += output[i];
    }
    for (int i = 0; i < size; i++)
        output[i] /= sum;
}

// ─────────────────────────────────────────────────────────────────────────────
// Main inference
// ─────────────────────────────────────────────────────────────────────────────
void run_inference(void)
{
    memset(conv1_buf, 0, CONV1_OUT * 64 * 64 * sizeof(float));
    memset(conv2_buf, 0, CONV2_OUT * 32 * 32 * sizeof(float));
    memset(conv3_buf, 0, CONV3_OUT * 16 * 16 * sizeof(float));
    memset(gap_buf,   0, CONV3_OUT * sizeof(float));
    memset(fc_out,    0, FC_OUT    * sizeof(float));

    // ── Verify blob is embedded correctly ────────────────────────────────────
    int blob_size = (int)(model_weights_bin_end - model_weights_bin_start);
    ESP_LOGI(TAG, "DEBUG: blob size = %d bytes (expected 23491)", blob_size);
    if (blob_size != 23491) {
        ESP_LOGE(TAG, "WRONG BLOB SIZE — model_weights.bin not embedded correctly, aborting");
        return;
    }

    // ── Capture frame ────────────────────────────────────────────────────────
    esp_err_t err = camera_get_frame_uint8(im, IN_H * IN_W);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "Camera frame capture failed, skipping inference");
        return;
    }

    // ── Normalise to [0, 1] ───────────────────────────────────────────────────
    for (int i = 0; i < IN_H * IN_W; i++)
        image_fp[i] = (float)im[i] / 255.0f;

    const int8_t *bin = model_weights_bin_start;
    int off = 0;

    // ── Block 1:
    conv(image_fp, conv1_buf,
         bin + off + CONV2D_6_BIAS_QUANTIZED_SIZE,  
         bin + off,                                  
         conv2d_6_weight_scale, conv2d_6_bias_scale,
         IN_CH, CONV1_OUT, 64, 64, 3, 3, 1);
    off += CONV2D_6_BIAS_QUANTIZED_SIZE + CONV2D_6_WEIGHT_QUANTIZED_SIZE;  // off = 160

  
    relu(conv1_buf, CONV1_OUT * 64 * 64);
    maxpool2x2(conv1_buf, conv1_buf, CONV1_OUT, 64, 64);


    // ── Block 2:
    conv(conv1_buf, conv2_buf,
         bin + off + CONV2D_7_BIAS_QUANTIZED_SIZE,
         bin + off,
         conv2d_7_weight_scale, conv2d_7_bias_scale,
         CONV1_OUT, CONV2_OUT, 32, 32, 3, 3, 1);
    off += CONV2D_7_BIAS_QUANTIZED_SIZE + CONV2D_7_WEIGHT_QUANTIZED_SIZE;  // off = 4800

   
    relu(conv2_buf, CONV2_OUT * 32 * 32);
    maxpool2x2(conv2_buf, conv2_buf, CONV2_OUT, 32, 32);

    // ── Block 3: conv2d_8 ─────────────────────────────────────────────────────
    conv(conv2_buf, conv3_buf,
         bin + off + CONV2D_8_BIAS_QUANTIZED_SIZE,
         bin + off,
         conv2d_8_weight_scale, conv2d_8_bias_scale,
         CONV2_OUT, CONV3_OUT, 16, 16, 3, 3, 1);
    off += CONV2D_8_BIAS_QUANTIZED_SIZE + CONV2D_8_WEIGHT_QUANTIZED_SIZE;  // off = 23296

    relu(conv3_buf, CONV3_OUT * 16 * 16);
    maxpool2x2(conv3_buf, conv3_buf, CONV3_OUT, 16, 16);

    // ── GAP + FC ──────────────────────────────────────────────────────────────
    global_avg_pool(conv3_buf, gap_buf, CONV3_OUT, 8, 8);

    fc(gap_buf, fc_out, CONV3_OUT, FC_OUT,
       bin + off + DENSE_2_BIAS_QUANTIZED_SIZE,
       bin + off,
       dense_2_weight_scale, dense_2_bias_scale);

    // ── Softmax + argmax ──────────────────────────────────────────────────────
    float probabilities[FC_OUT];
    softmax(fc_out, probabilities, FC_OUT);

    int   pred_class = 0;
    float max_prob   = probabilities[0];
    for (int i = 1; i < FC_OUT; i++) {
        if (probabilities[i] > max_prob) {
            max_prob   = probabilities[i];
            pred_class = i;
        }
    }

    strncpy(s_last_prediction.class_name, CLASS_NAMES[pred_class],
            sizeof(s_last_prediction.class_name) - 1);
    s_last_prediction.class_name[sizeof(s_last_prediction.class_name) - 1] = '\0';
    s_last_prediction.confidence = max_prob;
    for (int i = 0; i < FC_OUT; i++)
        s_last_prediction.prob[i] = probabilities[i];

    printf("\n=== Prediction ===\n");
    for (int i = 0; i < FC_OUT; i++)
        printf("  %-10s %5.1f%%%s\n",
               CLASS_NAMES[i],
               probabilities[i] * 100.0f,
               (i == pred_class) ? "  <" : "");
    printf("  Confidence: %.1f%%\n", max_prob * 100.0f);
    printf("==================\n\n");
}