# -*- coding: utf-8 -*-
"""fault_simulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dHIdN9veCKJulnw2LmJEuYR5803C8ay5
"""

#gate evaluation
def eval_gate(gate, values):
    if gate == "AND":
        return int(all(values))
    elif gate == "OR":
        return int(any(values))
    elif gate == "NAND":
        return int(not all(values))
    elif gate == "NOR":
        return int(not any(values))
    elif gate == "XOR":
        return int(sum(values) % 2)
    elif gate == "NOT":
        return int(not values[0])
    elif gate == "BUF":
        return int(values[0])


#circuit simulator
def simulate_circuit(input_vector):
    values = dict(zip(inputs, input_vector))
    remaining_gates = gates.copy()
    while remaining_gates:
        next_remaining = []
        for left, gate, params in remaining_gates:
            if all(p in values for p in params):
                in_vals = [values[p] for p in params]
                values[left] = eval_gate(gate, in_vals)
            else:
                next_remaining.append((left, gate, params))
            remaining_gates = next_remaining
    result = {out: values.get(out, 'X') for out in outputs}
    return result

#fault list generation
def generate_faultlist(inputs, gates, outputs):
    faultlist = []
    count = 0
    nodes = set(inputs)
    for left, gate, params in gates:
        nodes.add(left)
    for node in nodes:
        faultlist.append(f"{node}-0")
        faultlist.append(f"{node}-1")
        count += 2

    for left, gate, params in gates:
        for p in params:
            faultlist.append(f"{left}-{p}-0")
            faultlist.append(f"{left}-{p}-1")
            count += 2
    for out in outputs:
        faultlist.append(f"{out}-out-0")
        faultlist.append(f"{out}-out-1")
        count+=2
    faults_str = ",".join(faultlist)
    return faults_str, count

#fault detection
def fault_detection(input_vector, fault):
    notD = fault_sim(input_vector, fault=None)
    D = fault_sim(input_vector, fault=fault)
    for node in outputs:
        if notD.get(node) != D.get(node):
            return True
    return False

#fault simulator
def fault_sim(input_vector, fault=None):
    values = dict(zip(inputs, input_vector))
    if fault:
        if fault.endswith("-0") or fault.endswith("-1"):
            node = fault.split("-")[0]
            stuck_val = int(fault[-1])
            if node in inputs:
                values[node] = stuck_val

    remaining_gates = gates.copy()
    while remaining_gates:
        next_remaining = []
        for left, gate, params in remaining_gates:
            if all(p in values for p in params):
                in_vals = []
                for p in params:
                      val = values[p]

                      if fault == f"{p}-0" or fault == f"{left}-{p}-0":
                              val = 0
                      elif fault == f"{p}-1" or fault == f"{left}-{p}-1":
                              val = 1
                      in_vals.append(val)
                out_val = eval_gate(gate, in_vals)
                if fault == f"{left}-0" or fault == f"{left}-{gate}-0" or fault == f"{left}-out-0":
                    out_val = 0
                elif fault == f"{left}-1" or fault == f"{left}-{gate}-1" or fault == f"{left}-out-1":
                    out_val = 1
                values[left] = out_val
            else:
                next_remaining.append((left, gate, params))

        remaining_gates = next_remaining
    for out in outputs:
      if fault == f"{out}-0" or fault == f"{out}-out-0":
        values[out] = 0
      elif fault == f"{out}-1" or fault == f"{out}-out-1":
        values[out] = 1
    return values

#main function
inputs, outputs, gates = [], [], []
levels = {}
input_vector = []
with open("/content/p2.bench", "r") as f:
    for line in f:
        line = line.strip()
        if line.startswith("INPUT"):
            node = line[6:-1]
            inputs.append(node)
            levels[node] = 0
        elif line.startswith("OUTPUT"):
            node = line[7:-1]
            outputs.append(node)
        elif "=" in line:
            left, right = line.split("=")
            left = left.strip()
            gate, params = right.strip().split("(")
            params = params[:-1].split(",")
            params = [p.strip() for p in params]
            gates.append((left, gate, params))
updated = True
while updated:
    updated = False
    for left, gate, params in gates:
        if left not in levels:
            ready = True
            for p in params:
                if p not in levels:
                    ready = False
                    break
            if ready:
                max = 0
                for p in params:
                    if levels[p] > max:
                        max = levels[p]
                levels[left] = max + 1
                updated = True

faults, total = generate_faultlist(inputs, gates, outputs)
print(f"\nTotal number of faults: {total}")
print("\nFull Fault List:")
for f in faults.split(","):
    print(f)

print(f"\nInputs: {inputs}")
vec = input(f"Enter input vector for {len(inputs)} inputs: ").strip().lower()

if vec.startswith("0x"):
    invec = bin(int(vec, 16))[2:].zfill(len(inputs))
    invec = invec[::-1]
else:
    invec = vec.zfill(len(inputs))
input_vector = [int(b) for b in invec]
outputs_result = simulate_circuit(input_vector)

print("\nCircuit Simulation Result:")
for out in outputs:
        print(f"{out} = {outputs_result[out]}")

print("\nChoose fault simulation mode:")
print("1. Single fault (any TV, any fault)")
print("2. All faults (any TV, all faults)")
choice = input("Enter 1 or 2: ").strip()

if choice == "1":
    fault = input("Enter fault: ").strip()
    detected = fault_detection(input_vector, fault)
    print(f"\nFault {fault} detected by TV {input_vector}: {detected}")

elif choice == "2":
    faults_list = faults.split(",")
    covered = 0
    print("\nFault Simulation Results:")
    for f in faults_list:
        if fault_detection(input_vector, f):
            print(f"{f}: DETECTED")
            covered += 1
        else:
            print(f"{f}: NOT DETECTED")
    coverage_percent = covered / total * 100
    print(f"\nTotal faults detected: {covered}/{total} ({coverage_percent:.2f}%)")

else:
    print("Invalid choice")


