# -*- coding: utf-8 -*-
"""ECE594.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jVb0E7orpcMFEOEKoJtMrB5iTfKsa8jM
"""

#written by Domink Kornak, JPG to 32x32x3 binary file converter
import numpy as np
from PIL import Image
import torchvision.transforms as transforms
import struct
import os

IMG_PATH = "dogcifar.jpg"

# Load and preprocess image
img = Image.open(IMG_PATH).convert("RGB")
img = img.resize((32, 32), Image.BILINEAR)

# Convert to tensor (float32)
transform = transforms.ToTensor()
img_tensor = transform(img)

# Quantize to int8
img_int8 = (img_tensor * 255 - 128).numpy().astype(np.int8)
img_flat = img_int8.flatten()

# Generate output file name: name_image.bin
base_name = os.path.splitext(os.path.basename(IMG_PATH))[0]
# Remove 'cifar' if present
base_name = base_name.replace("cifar", "")
OUTPUT_BIN = f"{base_name}_image.bin"

# Write binary file
with open(OUTPUT_BIN, "wb") as f:
    for val in img_flat:
        f.write(struct.pack("b", val))

print(f"Binary file generated: {OUTPUT_BIN}")