# -*- coding: utf-8 -*-
"""CircuitTestabilityAnalyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HWN8yClba33K8hSIrMSrF7q5IYg_hoD6
"""

import random
#gate evaluation
def eval_gate(gate, values):
    if gate == "AND":
        return int(all(values))
    elif gate == "OR":
        return int(any(values))
    elif gate == "NAND":
        return int(not all(values))
    elif gate == "NOR":
        return int(not any(values))
    elif gate == "XOR":
        return int(sum(values) % 2)
    elif gate == "NOT":
        return int(not values[0])
    elif gate == "BUF":
        return int(values[0])

#circuit simulator
def simulate_circuit(input_vector, nodes_to_track=None):
    values = dict(zip(inputs, input_vector))
    remaining_gates = gates.copy()
    while remaining_gates:
        next_remaining = []
        for left, gate, params in remaining_gates:
            if all(p in values for p in params):
                in_vals = [values[p] for p in params]
                values[left] = eval_gate(gate, in_vals)
            else:
                next_remaining.append((left, gate, params))
        remaining_gates = next_remaining
    if nodes_to_track is None:
        nodes_to_track = values.keys()
    return {node: values[node] for node in nodes_to_track}

# SCOAP
def controllability():
    c0 = {node: 1 if node in inputs else 0 for node in levels}
    c1 = {node: 1 if node in inputs else 0 for node in levels}
    sorted_nodes = sorted(levels.items(), key=lambda x: x[1])
    for node, _ in sorted_nodes:
        for left, gate, params in gates:
            if left == node:
                if gate == "AND":
                    c0[node] = 1 + min(c0[p] for p in params)
                    c1[node] = 1 + sum(c1[p] for p in params)
                elif gate == "OR":
                    c0[node] = 1 + sum(c0[p] for p in params)
                    c1[node] = 1 + min(c1[p] for p in params)
                elif gate == "NAND":
                    c0[node] = 1 + sum(c1[p] for p in params)
                    c1[node] = 1 + min(c0[p] for p in params)
                elif gate == "NOR":
                    c0[node] = 1 + min(c1[p] for p in params)
                    c1[node] = 1 + sum(c0[p] for p in params)
                elif gate == "XOR":
                    c0[node] = 1 + min(sum(c0[p] for p in params), sum(c1[p] for p in params))
                    c1[node] = 1 + min(c0[params[0]] + c1[params[1]], c1[params[0]] + c0[params[1]])
                elif gate == "NOT":
                    c0[node] = 1 + c1[params[0]]
                    c1[node] = 1 + c0[params[0]]
                elif gate == "BUF":
                    c0[node] = 1 + c0[params[0]]
                    c1[node] = 1 + c1[params[0]]
    return c0, c1

# MC
def mc_simulation(samples=1000):
    node_counts = {node: [0, 0] for node in levels}
    for _ in range(samples):
        vec = [random.randint(0, 1) for _ in inputs]
        result = simulate_circuit(vec, nodes_to_track=levels.keys())
        for node, val in result.items():
            node_counts[node][val] += 1
    node_probs = {}
    for node, (count0, count1) in node_counts.items():
        node_probs[node] = (count0/samples, count1/samples)

    return node_probs

# MAIN
inputs, outputs, gates = [], [], []
levels = {}

with open("/content/c432.bench", "r") as f:
    for line in f:
        line = line.strip()
        if line.startswith("INPUT"):
            node = line[6:-1]
            inputs.append(node)
            levels[node] = 0
        elif line.startswith("OUTPUT"):
            node = line[7:-1]
            outputs.append(node)
        elif "=" in line:
            left, right = line.split("=")
            left = left.strip()
            gate, params = right.strip().split("(")
            params = params[:-1].split(",")
            params = [p.strip() for p in params]
            gates.append((left, gate, params))

updated = True
while updated:
    updated = False
    for left, gate, params in gates:
        if left not in levels:
            ready = True
            for p in params:
                if p not in levels:
                    ready = False
                    break
            if ready:
                max = 0
                for p in params:
                    if levels[p] > max:
                        max = levels[p]
                levels[left] = max + 1
                updated = True

c0, c1 = controllability()
mc_prob = mc_simulation(samples=1000)

print("SCOAP RESULTS")
print(f"{'Node':<8}{'c0':<8}{'c1':<8}")
for node in sorted(levels, key=lambda n: levels[n]):
    print(f"{node:<8}{c0[node]:<8}{c1[node]:<8}")
print("\nMONTE CARLO RESULTS")
print(f"{'Node':<8}{'p0':<8}{'p1':<8}")
for node in sorted(levels, key=lambda n: levels[n]):
    p0, p1 = mc_prob[node]
    print(f"{node:<8}{p0:<8.3f}{p1:<8.3f}")